### ISSUE TITLE
Default to preset es2015 if not a supported version

### ISSUE THREAD

**Issue by Salakar** [jhen0409/babel-preset-es2015-node-auto#2]
Would it be possible to have it default to preset `es2015` if it's not a supported version?

I can do a PR if need be, just getting your thoughts?

**Comment by jhen0409** [comment]
Agree, we can do. 👍

**Comment by Salakar** [comment]
Want me to do a PR or are you happy to do it?

**Comment by jhen0409** [comment]
Done. Published in `v0.0.4`.

**Comment by Salakar** [comment]
Nice!
